### ISSUE TITLE
Command changes

### ISSUE THREAD

**Issue by thomascobb** [PandABlocks/PandABlocks-client#26]
- Rename `GetBlockNumbers` to  `GetBlockInfo` and make it return `Dict[str, BlockInfo]` where `BlockInfo` has `number` and `description`
- Rename `FieldType` to `FieldInfo` and add `description` and `labels`, rename `GetFields` to `GetFieldInfo` and make it do the `*DESC` and `*ENUM` commands that https://github.com/dls-controls/pymalcolm/blob/b6b5671cce204ed88bb61f9af899e45190591ab9/malcolm/modules/pandablocks/pandablocksclient.py#L206 does

**Comment by AlexanderWells-diamond** [comment]
This issue is being worked on in PR #25. 

This will also obviously include testing for both of these methods, at least one new Example script (mostly so I can test against a real PandA as I go) and probably some more documentation regarding how to introspect a PandA in how-to or explanation format.
