### ISSUE TITLE
LICENSE missing for sdist

### ISSUE THREAD

**Issue by beenje** [PandABlocks/PandABlocks-client#37]
The LICENSE file is still missing from the sdist 0.3.1 on pypi.

I'm not sure why. New versions of setuptools should automatically include it. If I run `pyproject-build` locally in the repo, the LICENSE is included.

Was the version uploaded to pypi created differently?

**Comment by AlexanderWells-diamond** [comment]
The version uploaded to PyPi is built in our [Github CI here](https://github.com/PandABlocks/PandABlocks-client/blob/master/.github/workflows/code.yml#L38). I'm afraid I have no idea why a licence file isn't being added. @coretl any ideas?

**Comment by coretl** [comment]
The issue is probably the pinned early versions of setuptools to keep compatibility with our internal build process. As we don't need to do that for this particular module then I think we can safely update. For best results, maybe we should adopt https://github.com/DiamondLightSource/python3-pip-skeleton when @gilesknap has finished the latest round of updates

**Comment by beenje** [comment]
I just checked 0.7.0 and the file is present. Was maybe before (probably at least since you switched to setuptools_scm). Anyway, closing this!
